### PR TITLE
Closes #50, updated Conquistador text to be more accurate

### LINKED ISSUE #50: Investigate: Religion disappears sometimes when conquering/losing a city
image

### PR DESCRIPTION
**Pull request by puj**
Conquistadors should convert captured cities to the founded religion of Spain.

However, the `DynamicModifier` `EFFECT_ADJUST_CITY_RELIGION_ON_CAPTURE` uses 
the **Majority** religion of the player
NOT the **Founded** religion.  

Not much we can do about that, so we change the text to be more accurate.
image

### CODE REVIEW

**Comment by iElden** [comment]
"adopt the Conquistador player's Religion (if it is the majority religion in their empire)"
If an other religion is the majority on the spain empire, is this religion apllied to the captured city ? If no, it's the right description, if yes, "adoprt the conquistador player's majority religion" should be a better translate.

**Review by iElden — CHANGES_REQUESTED** [review]
English LOC has been update without updated other LOC files

**Comment by puj** [comment]
Fixed

**Review by iElden — APPROVED** [review]
Can't find the original version of korean, leave at this in text file

**Pull request merged**
